security:
  oauth2:
    client:
      clientId: account-service
      clientSecret: ${ACCOUNT_SERVICE_PASSWORD}
      accessTokenUri: http://auth-service:5000/uaa/oauth/token
      grant-type: client_credentials
      scope: server
    resource:
      user-info-uri: http://auth-service:5000/uaa/users/current

spring:
  data:
    mongodb:
      host: account-mongodb
      username: user
      password: ${MONGODB_PASSWORD}
      database: piggymetrics
      port: 27017
  cloud:
    openfeign:
      circuitbreaker:
        enabled: true
  security:
    oauth2:
      client:
        registration:
          account-service:
            client-id: account-service
            client-secret: ${ACCOUNT_SERVICE_PASSWORD}
            authorization-grant-type: client_credentials
            scope: server
            provider: auth-service
        provider:
          auth-service:
            token-uri: http://auth-service:5000/uaa/oauth/token

resilience4j:
  timelimiter:
    configs:
      default:
        timeout-duration: 10s

server:
  servlet:
    context-path: /accounts
  port: 6000
